---
- name: Obtem a versao do Fedora
  ansible.builtin.set_fact:
    system_fedora_version: "{{ ansible_distribution_major_version }}"

- name: Instala o RPM Fusion Free
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
    disable_gpg_check: true
  loop:
    - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ system_fedora_version }}.noarch.rpm"
    - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ system_fedora_version }}.noarch.rpm"
