---
- name: Create user account
  ansible.builtin.user:
    name: '{{ item.name }}'
    groups: '{{ item.groups | join(",") }}'
    shell: '{{ item.shell | default("/bin/bash") }}'
    password: '{{ item.password }}'
    state: present
  loop: '{{ user_accounts }}'
