---
- name: Remove unused packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: absent
  loop:
    - gnome-connections
    - gnome-maps
    - libreoffice-core
    - mediawriter
    - rhythmbox

- name: Install required packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - dnf-plugins-core
    - docker-compose
    - gnome-tweaks
    - gnome-theme-extra
    - google-chrome-stable
    - libvirt
    - neovim
    - nodejs
    - papirus-icon-theme
    - plocate
    - python3-neovim
    - python3-pip
    - rsms-inter-fonts
    - tailscale
    - tmux
    - vagrant
    - vagrant-libvirt
    - virt-manager

- name: Include TickTick tasks
  ansible.builton.include_tasks: ticktick.yml
