---
- name: Remove unused packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: absent
    allowerasing: true
  loop:
    - gnome-boxes
    - gnome-connections
    - gnome-maps
    - gnome-tour
    - libreoffice-core
    - mediawriter
    - rhythmbox
    - yelp

- name: Install required packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - dnf-plugins-core
    - docker-compose
    - gnome-tweaks
    - gnome-themes-extra
    - google-chrome-stable
    - libvirt
    - neovim
    - nodejs
    - papirus-icon-theme
    - plocate
    - python3-neovim
    - python3-pip
    - rsms-inter-fonts
    - tailscale
    - tmux
    - vagrant
    - vagrant-libvirt
    - virt-manager

- name: Install VS Code
  ansible.builtin.dnf:
    name: code
    state: present
    update_cache: true
