---
- name: Remove unused packages
  ansible.builtin.dnf:
    name:
      - firefox
      - gnome-boxes
      - gnome-connections
      - gnome-maps
      - gnome-tour
      - libreoffice-core
      - mediawriter
      - rhythmbox
      - yelp
    state: absent
    allowerasing: true

- name: Config repositories
  ansible.builtin.import_tasks: repos.yml

- name: Install required packages
  ansible.builtin.dnf:
    name:
      - alacritty
      - chezmoi
      - dnf-plugins-core
      - docker-compose
      - golang
      - gnome-tweaks
      - nodejs
      - plocate
      - python3-neovim
      - python3-pip
      - vagrant
      - vagrant-libvirt
      - zsh
    state: present

- name: Install multimedia package group
  ansible.builtin.dnf:
    name: '@Multimedia'
    state: present
    install_weak_deps: false
    exclude:
      - 'PackageKit-gstreamer-plugin'

- name: Install FFmpeg codecs
  ansible.builtin.dnf:
    name: ffmpeg
    state: present
    allowerasing: true
