---
- name: Install TickTick
  become: true
  ansible.builtin.dnf:
    name: "{{ packages_ticktick_url }}"
    state: present
    disable_gpg_check: true

- name: Config iptables in libvirt firewall
  become: true
  ansible.builtin.lineinfile:
    path: /usr/share/applications/ticktick.desktop
    regexp: '^Icon=ticktick$'
    line: 'Icon=com.ticktick.TickTick'
  register: libvirt_firewall
