---
- name: Install TickTick package
  ansible.builtin.dnf:
    name: "{{ packages_ticktick_url }}"
    state: present
    disable_gpg_check: true

- name: Set TickTick desktop icon
  ansible.builtin.lineinfile:
    path: /usr/share/applications/ticktick.desktop
    regexp: '^Icon=ticktick$'
    line: 'Icon=com.ticktick.TickTick'
