---
- name: Configure VS Code repository
  ansible.builtin.copy:
    src: vscode.repo
    dest: /etc/yum.repos.d/vscode.repo
    mode: '644'
    owner: root
    group: root

- name: Install VS Code
  ansible.builtin.dnf:
    name: code
    state: present
    update_cache: true
