---
- name: Disable PyCharm COPR repository
  community.general.copr:
    name: phracek/PyCharm
    state: absent

- name: Disable ABRT service
  ansible.builtin.service:
    name: abrtd
    state: stopped
    enabled: false

- name: Remove Nvidia and Steam RPM Fusion repos
  ansible.builtin.file:
    path: "/etc/yum.repos.d/rpmfusion-nonfree-{{ item }}.repo"
    state: absent
  loop:
    - nvidia-driver
    - steam
