---
- name: Configura o repositório do Docker
  ansible.builtin.copy:
    src: docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: '644'
    owner: root
    group: root

- name: Instala o Docker
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - containerd.io
    - docker-buildx-plugin
    - docker-ce
    - docker-ce-cli
    - docker-compose-plugin
