---
- name: Executa as tarefas de limpeza
  ansible.builtin.include_tasks: clean.yml

- name: Ativa os pacotes RPM fusion
  ansible.builtin.include_tasks: rpmfusion.yml

- name: Instala/Remove pacotes necessários
  ansible.builtin.include_tasks: packages.yml

- name: Instala os flatpaks necessários
  ansible.builtin.include_tasks: flatpaks.yml

- name: Instala o docker
  ansible.builtin.include_tasks: docker.yml

- name: Instala o MISE
  ansible.builtin.include_tasks: mise.yml

- name: Instala o VSCode
  ansible.builtin.include_tasks: vscode.yml

- name: Instala o TickTick
  ansible.builtin.include_tasks: ticktick.yml

- name: Configura o libvirt
  ansible.builtin.include_tasks: libvirt.yml
