---
- name: Install Homebrew dependencies
  ansible.builtin.dnf:
    name: '@Development Tools'
    state: present

- name: Check whether Homebrew is installed
  ansible.builtin.stat:
    path: /home/linuxbrew/.linuxbrew/bin/brew
  register: brew_global_bin

- name: Install Homebrew
  become: true
  become_user: "{{ lookup('env', 'USER') }}"
  ansible.builtin.shell: >
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: not brew_global_bin.stat.exists
  args:
    creates: "/home/linuxbrew/.linuxbrew/bin/brew"
  environment:
    NONINTERACTIVE: "1"

- name: Create linuxbrew group
  ansible.builtin.group:
    name: linuxbrew
    state: present

- name: Set Homebrew directory group ownership
  ansible.builtin.file:
    path: /home/linuxbrew
    owner: root
    group: linuxbrew
    recurse: true
    mode: '775'
