---
- name: Deploy GNOME and GDM dconf settings
  ansible.builtin.copy:
    src: 99-custom-settings.conf
    dest: '{{ item }}/99-custom-settings.conf'
    owner: root
    group: root
    mode: '644'
  loop:
    - '/etc/dconf/db/local.d'
    - '/etc/dconf/db/gdm.d'
  notify:
    - Reset GNOME settings
    - Update dconf database
