---
- name: Enable SSH service
  ansible.builtin.service:
    name: sshd
    state: started
    enabled: true
  when: services_enable_ssh

- name: Enable Tailscale service
  ansible.builtin.service:
    name: tailscaled
    state: started
    enabled: true

- name: Disable ABRT service
  ansible.builtin.service:
    name: abrtd
    state: stopped
    enabled: false
