---
- name: Instala os flatpaks necessarios
  community.general.flatpak:
    name: "{{ item }}"
    state: present
  loop:
    - com.bitwarden.desktop
    - com.discordapp.Discord
    - com.spotify.Client
    - com.ticktick.TickTick
    - io.dbeaver.DBeaverCommunity
    - io.ente.auth
    - io.gitlab.adhami3310.Impression
    - io.podman_desktop.PodmanDesktop
    - org.localsend.localsend_app
    - org.onlyoffice.desktopeditors
    - org.remmina.Remmina
    - org.videolan.VLC
    - md.obsidian.Obsidian
